Issue 1334 Refactor Block Editor Flow
Datawheel/canon pull request #1337
Opened 2022-01-14 23:00 UTC by greenrhyno

Closes #1334 

Improves handling of branching BlockType-specific logic by making the delegation of responsibilities of various components related to block editing clearer.

Changes include:
- simplification and consolidation of block content editing methods
- expansion of `SimpleUI` to choose between custom UI editors or a generic `RichTextEditor`
- reduction of passed props by use of shared selector hooks (e.g. `useVariables`, `useBlocks`)
- reorganization of special BlockType-specific logic in `BlockPreview` into separate `BlockPreviewAdapter` files
- addition of logic to allow editor components to set a `isValid` state to avoid the saving on invalid intermediate states
- addition of JSDoc types for clearer function signatures

2022-01-14 23:03 UTC, greenrhyno commented
working on merge :( will finish monday

2022-01-18 15:48 UTC, greenrhyno commented
> working on merge :( will finish monday

Finished 💪

2022-01-19 16:22 UTC, jhmullen requested changes

2022-01-19 16:22 UTC, jhmullen commented on packages/reports/src/utils/consts/cms.js
> +  SELECTOR: "selector", // TODO - move to logic types
Let's either:
1) change this to `todo1.0` which has been my standard so far
or, if `TODO` is a thing that is supported by github/typescript/vscode/your own heart
2) change all `todo1.0`'s to `TODO` and stick with that from now on.

2022-01-19 17:20 UTC, merged