Canon next 0.1.5
Datawheel/canon pull request #1379
Opened 2023-03-02 19:44 UTC by scespinoza

- Adds custom sections support.
- Improves ProfileSearch component

2023-03-03 21:52 UTC, davelandry requested changes
@scespinoza this is looking great, and it makes sense to me. I see what you mean about commenting out the customSections for now. Are you intending for me to merge/release this so we can get the ProfileSearch improvements, or do you want to keep working in here until you get CustomSections working? (if so, I'd also like you to add something to the README describing the folder/config settings needed!)

2023-03-03 21:52 UTC, davelandry commented on example-next/pages/profile/[...members].js
> +
...if I'm not merging right away, should we remove this line? 😏

2023-03-26 14:11 UTC, bidwolf commented
Hey guys, Good morning!
I'm working to update a new version of a Brazilian website: codelife.com that depends on canon's old versions to work.
I would like to maintain this partnership, I would love it if it were possible to integrate this framework with next-js and the new versions of react, so if I can help in any way I'm open to that.

2023-03-28 21:57 UTC, davelandry commented
hi @bidwolf! I just published a version of an internal guide we wrote to start migrating projects to Nextjs (and completely abandoning canon-core). Check it out, and if you have any questions please make a new Github issue in this repository and we can discuss/help!

https://github.com/Datawheel/canon/wiki/Migrating-from-canon-to-Next.js

2023-03-29 19:20 UTC, davelandry approved these changes

2023-03-29 19:22 UTC, merged